### PR TITLE
[bugfix] change layer.interactive to layer.mouse_pan

### PR DESCRIPTION
**Pull request by psobolewskiPhD**
Closes: https://github.com/napari-threedee/napari-threedee/issues/152

In https://github.com/napari/napari/pull/5701 (released in 0.4.18) the layer property `interactive` was deprecated. This results in a spam of FutureWarnings, which are annoying if using napari-threedee in a notebook.

In this PR, I replace the usage of `layer.interactive` with `layer.mouse_pan`, as instructed by https://github.com/napari/napari/pull/5701

### CODE REVIEW

**Review by alisterburt — APPROVED** [review]

**Comment by alisterburt** [comment]
not sure what's going on with the tests but the code looks good - will chase this up

**Comment by psobolewskiPhD** [comment]
So looking into this locally, python 3.9, napari 0.4.18 everything passes.
With 0.4.19:
```
FAILED src/napari_threedee/visualization/_tests/test_camera_spline.py::test_annotate_spline - ValueError: operands could not be broadcast together with shapes (3,) (4,)
FAILED src/napari_threedee/visualization/_tests/test_camera_spline.py::test_spline_explore - ValueError: operands could not be broadcast together with shapes (3,) (4,)
```

It's failing on adding points to existing layer:
```
points_layer.add(np.random.random((4, 3)))
```
But I can't find anything different about the layers created prior.

I'll try some git bisect.

**Comment by psobolewskiPhD** [comment]
Here's the capri commit which triggers the test fails:
cc658340ae8a98a40ffe740081af060a992fc80e
PR: https://github.com/napari/napari/pull/6098

Ok, so the PR made it that points are selected in the add() method, which is what is used in the test:
https://github.com/napari/napari/pull/6098/files
If you use `np.append` in the test instead, then it passes.

But the real issue is that when you use `camera_spline.enabled = True` and then add some points to the empty layer and try to select them you get the traceback.
here's a script reproducer (it's the test basically that passes):
```
import napari
from typing import Tuple

import numpy as np

from napari_threedee.annotators import PathAnnotator
from napari_threedee.annotators.constants import N3D_METADATA_KEY
from napari_threedee.data_models import N3dPaths
from napari_threedee.visualization.camera_spline import CameraSpline, CameraSplineMode

viewer = napari.Viewer()
camera_spline = CameraSpline(viewer=viewer)

# add an image layer to the viewer
plane_parameters_z = {
    'position': (15, 15, 15),
    'normal': (1, 0, 0),
    'thickness': 10,
}
image_layer = viewer.add_image(np.random.random((30, 30, 30)), plane=plane_parameters_z)

camera_spline.set_layers(image_layer)

# enter annotation mode
camera_spline.enabled = True
camera_spline.mode = "annotate"

# get the points layer
points_layer = camera_spline.spline_annotator_model.points_layer

# add 4 points and check that the spline was created
#points_layer.add(np.random.random((4, 3)))
points_layer.data = np.append(points_layer.data, np.atleast_2d(np.random.random((4, 3))), axis=0)
napari.run()
```
You will need to go to the 0 slice to find the points.

**Comment by alisterburt** [comment]
thanks for digging @psobolewskiPhD - seems like this is broken on the napari side then? `Points.add()` should be able to accept multiple points, right?

**Comment by alisterburt** [comment]
in any case: n3d doesn't actually require adding multiple points at once so we should be able to merge this if you have a way of making the test pass... maybe just add all points one by one?

**Comment by psobolewskiPhD** [comment]
@alisterburt It's not adding the points that's failing, it's *selecting them*.
So it's this in napari:
https://github.com/napari/napari/blob/8f8d42031a319ce3295ee9aea77b143b782b92c7/napari/layers/points/points.py#L1469

Specifically the interaction with properties
https://github.com/napari/napari/blob/8f8d42031a319ce3295ee9aea77b143b782b92c7/napari/layers/points/points.py#L1512-L1517

Definitely this is a separate issue from the FutureWarning--I get it with the this tutorial:
https://napari-threedee.github.io/how_to/spline_annotator/
(`python spline_annotator_plugin.py`)

So maybe the best plan is:
Make a new issue with the various notes I have here -- higher visibility?

**Comment by kevinyamauchi** [comment]
@psobolewskiPhD , thanks for this PR! I _think_ I fixed the test issue in #160 and the tests are now passing on `main.` Would you mind merging main in and checking if things are working as expected?

**Review by kevinyamauchi — APPROVED** [review]
Thanks @psobolewskiPhD ! This LGTM. I'll merge now and make a release.

**Pull request merged**
