### PR TITLE
nd-ify the plane point annotator

### PR DESCRIPTION
**Pull request by alisterburt**
This PR makes our plane point annotator compatible with nD data

The only restriction at the minute is that the points and image layers must have the same dimensionality

### CODE REVIEW

**Review by kevinyamauchi — COMMENTED** [review]
This looks good to me! I think we should add a couple of tests before merging. I know we don't really have tests in general at the moment, but since we're moving towards 0.1, I think we should start at least adding them when we add new features to reduce the amount we have to backfill.

**Comment by alisterburt** [comment]
Thanks @kevinyamauchi - tests added! I can't reproduce the test failures from CI locally but also not sure what to do about them, any ideas? 'InvocationError'

**Comment by kevinyamauchi** [comment]
@alisterburt, I think it's an issue with the vm setup for the CI. I made a PR to update the python and qt setup to match the current plugin cookiecutter in #55. Can you have a look over there and merge if it looks good?

**Comment by alisterburt** [comment]
not sure why the diff is showing your PRs from main after rebase but thanks for fixing the CI, all good here now I hope?

**Review by kevinyamauchi — APPROVED** [review]
Looks good to me! Thanks for adding all of those tests!

**Comment by alisterburt** [comment]
@kevinyamauchi just needed a little push 😉

**Pull request merged**
