### PR TITLE
fix tests for napari 0.5.0

### PR DESCRIPTION
**Pull request by alisterburt**
this test passed on napari 0.4.19 but failed on 0.5.0

I think there were expectations in this test that I'm not sure should work - that you can annotate into a points layer with an arbitrary transform

Here I modify the test so that the layer you are annotating can have the arbitrary scale, but the points will be in world coordinates

### CODE REVIEW

**Comment by kevinyamauchi** [comment]
Thanks @alisterburt ! i agree that the points should be in world coordinates.

What do you mean by "annotate into a points layer with an arbitrary transform"? What is an example of an "arbitrary" transformation that doesn't work that is supported by napari?

**Comment by alisterburt** [comment]
in this case scale != [1, 1, 1] 

The point is more general though, what coordinate system are we annotating into? We agreed on zulip that all annotations should be in world coordinates (what we see) so adding points into a layer a transform doesn't make much sense to me

**Comment by alisterburt** [comment]
actually: it makes sense - it's just a whole bunch of complexity I'd rather not take on until we find we absolutely need it for something

**Comment by alisterburt** [comment]
@aysecanuenal just so you're aware, a small bug in the layer creation methods on `N3dDipoles` was causing the docs tests to fail (a test checks that examples execute without error) so I fixed it here. This touches code you've likely also touched so you will need to rebase your branch onto main once this has gone in

**Pull request merged**
