### PR TITLE
[WIP] add visualisation of click-plane for debugging

### PR DESCRIPTION
**Pull request by alisterburt**
this is a branch which adds visualisation of 
- the centroid of the clicked triangle
- the click point
- the view direction (as another point, further along the view direction)

This should allow us to debug the 'furthest away rotator is sometimes selected on click' bug

I'm struggling to figure out what exactly is wrong with what we're doing - switching to the maximum distance is clearly wrong and the signed distances appear to be calculated correctly... will keep investigating

### CODE REVIEW

**Comment by alisterburt** [comment]
Yes, I see that the wrong face is selected but haven't yet figured out why - I need to run some more careful tests on the signed distances but their calculation appears correct to me 🤷🏼‍♂️

**Comment by alisterburt** [comment]
it's also not always wrong, it's only under very specific circumstances I don't quite have a handle on yet 😆

**Comment by kevinyamauchi** [comment]
Hmm very strange...thanks for looking into it!

**Comment by alisterburt** [comment]
closing because moving to new manipulator model which fixes this

**Pull request closed without merging**
