### PR TITLE
Add implementation of dipole annotator

### PR DESCRIPTION
**Pull request by aysecanuenal**
Interactively adding and editing dipoles with dipole annotator 

:partying_face: 

[recording_dipole_annotator.webm](https://github.com/napari-threedee/napari-threedee/assets/150450168/722aa0f5-7feb-42a5-96e1-96d84932439b)

### CODE REVIEW

**Comment by alisterburt** [comment]
@aysecanuenal this is *wonderful*!! I had so much fun playing with it this morning - I think you've made something incredibly useful here

It looks like the test failure is during zarr creation, I assume this is because I wrote the export code when we had `N3dDipoles.napari_vectors` as a property and now we have an `N3dDipoles.as_napari_vectors()` methods - once that is fixed and tests are passing I think this is ready to go in!!

**Comment by kevinyamauchi** [comment]
Wow, this looks great! I love the direction setting of the dipole. Super cool stuff. Thanks, @aysecanuenal !

**Comment by aysecanuenal** [comment]
@kevinyamauchi  thanks a lot, your message made my morning :smiley:

**Comment by alisterburt** [comment]
@aysecanuenal test failures look unrelated, I've opened an issue at #250 to track so we can move forward here

**Pull request merged**
