### PR TITLE
[WIP] manipulator refactor

### PR DESCRIPTION
**Pull request by alisterburt**
Haven't been committing and want to keep track of where I'm at with this

- [x] separate models for manipulator/translator and associated visual data
- [x] add tests construction of models
- [x]  produce correct visual data from individual models
- [x] produce correct visual data from manipulator itself
- [x] hook up to Kevin's vispy visual
- [x] highlighting logic

### Also todo but maybe in separate PRs:
- [ ] hook up existing manipulators
- [ ] add docs

### CODE REVIEW

**Comment by alisterburt** [comment]
@kevinyamauchi just to check, is it right to say that which central axes are shown is implied by the set of translators/rotators used?

**Comment by kevinyamauchi** [comment]
> @kevinyamauchi just to check, is it right to say that which central axes are shown is implied by the set of translators/rotators used?

Yup! Each rotator and translator should specify a set of central axes they require. Then the included central axes would be the union of those sets.

**Comment by kevinyamauchi** [comment]
This looks great so far! Psyched to have this in, @alisterburt !

**Comment by kevinyamauchi** [comment]
> Also todo but maybe in separate PRs:
>
> hook up existing manipulators
> add docs

I am okay with doing both things in separate PRs. This is a solid chunk of work and the models stand alone (as the should).

**Comment by alisterburt** [comment]
okay, think this is ready for a review!

I realise this is a lot - feel free to optimistically merge/I'm happy to take you through it on Friday

https://user-images.githubusercontent.com/7307488/196538030-11eccc25-d104-4cca-808d-3912124d3062.mp4

**Review by kevinyamauchi — APPROVED** [review]
Amazing work, @alisterburt ! i think this is a lot cleaner. Quick question about the new directory structure. What is the intended usage of `napari_threedee/manipulator` and `napari_threedee/manipulators`? Is this just temporary as we transition to the new manipulator?

Would you mind just fixing the tests before merging? I think they are just failing because the kwargs haven't been updated to match the refactored components.

I am okay with an optimistic merge so that we can move forward!

**Comment by alisterburt** [comment]
Thanks @kevinyamauchi !

> Quick question about the new directory structure. What is the intended usage of `napari_threedee/manipulator` and `napari_threedee/manipulators`? Is this just temporary as we transition to the new manipulator?

It's temporary as you said but I'm not sure how this will pan out, where different manipulators should live vs the manipulator infra itself... will have a think in some followup.

In the meantime, I've fixed the tests here and will start on docs/hooking up our existing manipulators :)

**Pull request merged**
