### PR TITLE
[Docs] Remove the extra toc item and double header for the examples Gallery

### PR DESCRIPTION
**Pull request by psobolewskiPhD**
Currently the toc has an extra entry `Gallery for napari-threedee` that actually links back to the homepage. Also the header of the Gallery is duplicated. See:
image

In this PR I try to fix this by deleting the extra README which might be responsible.

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
OK, so the README has to be there. Trying to change the toc now

**Comment by psobolewskiPhD** [comment]
Ok, so changing the toc didn't do anything, just changed the name in the toc.
Looks like it's designed to have examples at the top level? Lets try that.

**Comment by psobolewskiPhD** [comment]
Ok, it's working. I will post some screenshots with the new look. I think it might be better? but can just as easily close this and leave it be.

**Comment by psobolewskiPhD** [comment]
The new look:
image

and if you scroll:
image

Both of the sub-menus work as before:
image


I put the plugin ones first, but could swap around to Library on top.

**Comment by GenevieveBuckley** [comment]
> Ok, so changing the toc didn't do anything, just changed the name in the toc. Looks like it's designed to have examples at the top level? Lets try that.

It is generally designed to have examples at the top level, but Keven asked me to keep separate subpages https://github.com/napari-threedee/napari-threedee/pull/104#issuecomment-1486274034

**Comment by psobolewskiPhD** [comment]
Fair enough. Closing.

**Pull request closed without merging**
