### PR TITLE
[WIP] add draft logo

### PR DESCRIPTION
**Pull request by kevinyamauchi**
this PR adds a WIP logo

threedee_logo_gradient

### CODE REVIEW

**Comment by alisterburt** [comment]
Very nice! Happy to merge but maybe we should leave here until we have something not WIP to keep the repo light? Up to you!

**Comment by kevinyamauchi** [comment]
Good point! Let's leave this WIP (converted to draft)

**Comment by alisterburt** [comment]
still love the concept - couple more designs from chatGPT, can vectorize any we like...

image
image
image
image

**Comment by psobolewskiPhD** [comment]
Of those above (the generated) the first one evokes the tree being a manipulator and there being planes to manipulate!
I kinda love it. Not sure about the blue all around the icon and whether the tree should stick out of the border of the icon, but those could maybe be tweaked?

**Comment by kevinyamauchi** [comment]
Cool stuff, @alisterburt ! I like the first and third one.

To be logo-ifiied, I think the first one would need to have the shadow removed and as @psobolewskiPhD said, it might be nice if the tree didn't go over the border.

For the third one, I think it's great as-is, just maybe remove the small bubbles.

**Comment by alisterburt** [comment]
done! 

n3d

**Comment by alisterburt** [comment]
hmm rough edge looks bad on dark mode, how about
image

**Comment by kevinyamauchi** [comment]
Ooo love it!

**Comment by kevinyamauchi** [comment]
@alisterburt , I think we should close this PR and make a new one with the new logo you just made. If it's just the png, I can make it, but if there are some other files (e.g., an illustrator or some other vector file), maybe you could make it?

**Pull request closed without merging**
