### PR TITLE
Bugfix: check if in 3D mode when loading widget (WIP)

### PR DESCRIPTION
**Pull request by psobolewskiPhD**
Closes: https://github.com/napari-threedee/napari-threedee/issues/169
Closes: https://github.com/napari-threedee/napari-threedee/issues/170

WIP

### CODE REVIEW

**Review by alisterburt — APPROVED** [review]
LGTM!

**Comment by alisterburt** [comment]
wait, still WIP? can you convert to draft?

**Comment by psobolewskiPhD** [comment]
It works, but if you have a layer in 2D mode, open the widget, then switch to 3D mode auto-activates because of:
https://github.com/napari-threedee/napari-threedee/blob/bf781477db969023891833a6bcc26acea0be1112/src/napari_threedee/manipulators/base_manipulator.py#L297-L302

I'm trying to work a way to not actually instantiate the manipulator from widget if in 2D mode

**Comment by psobolewskiPhD** [comment]
Hmm, it's not easy to fix and maybe it's OK? Let's see what it looks like that way.

**Comment by psobolewskiPhD** [comment]
OK, points mania is working, but layer is giving some errors. I'll poke around tomorrow.

**Comment by psobolewskiPhD** [comment]
So this sort of works, for the simple widgets, like manipulators. Basically check in the __init__ and don't even initialize the model and buttons if 2D. But it's a bit annoying I think to try to generalize and there is some moving of the elements.
I've made a similar alternative: https://github.com/napari-threedee/napari-threedee/pull/239

**Comment by alisterburt** [comment]
closing in favor of #239

**Pull request closed without merging**
